<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0">
<dict>
	<key>contexts</key>
	<dict>
		<key>characteristiks</key>
		<array>
			<dict>
				<key>match</key>
				<string> &gt; </string>
				<key>scope</key>
				<string>arror-right.characteristik.markdown-nice</string>
			</dict>
			<dict>
				<key>match</key>
				<string> &lt; </string>
				<key>scope</key>
				<string>arror-left.characteristik.markdown-nice</string>
			</dict>
			<dict>
				<key>match</key>
				<string>^\t{{ident}}</string>
				<key>scope</key>
				<string>intended.characteristik.markdown-nice</string>
			</dict>
			<dict>
				<key>match</key>
				<string>(http|https)://([a-zA-Z0-9\-\_\.\/\?\+\=\$\&\%\@\#\(\)])*</string>
				<key>scope</key>
				<string>link.characteristik.markdown-nice</string>
			</dict>
			<dict>
				<key>match</key>
				<string>\[</string>
				<key>push</key>
				<string>inside_string</string>
				<key>scope</key>
				<string>bracket-opening.characteristik.markdown-nice</string>
			</dict>
			<dict>
				<key>match</key>
				<string>\]</string>
				<key>pop</key>
				<true/>
				<key>scope</key>
				<string>bracket-closing.characteristik.markdown-nice</string>
			</dict>
		</array>
		<key>headlines</key>
		<array>
			<dict>
				<key>match</key>
				<string>^# </string>
				<key>scope</key>
				<string>first.headline.markdown-nice</string>
			</dict>
			<dict>
				<key>match</key>
				<string>^## </string>
				<key>scope</key>
				<string>second.headline.markdown-nice</string>
			</dict>
			<dict>
				<key>match</key>
				<string>^### </string>
				<key>scope</key>
				<string>third.headline.markdown-nice</string>
			</dict>
		</array>
		<key>inside_checkbox</key>
		<array>
			<dict>
				<key>match</key>
				<string> </string>
				<key>pop</key>
				<true/>
				<key>scope</key>
				<string>checkbox-empty.characteristik.markdown-nice</string>
			</dict>
			<dict>
				<key>match</key>
				<string>(x|X)</string>
				<key>pop</key>
				<true/>
				<key>scope</key>
				<string>checkbox-success.characteristik.markdown-nice</string>
			</dict>
			<dict>
				<key>match</key>
				<string>\-</string>
				<key>pop</key>
				<true/>
				<key>scope</key>
				<string>checkbox-wip.characteristik.markdown-nice</string>
			</dict>
			<dict>
				<key>match</key>
				<string>\!</string>
				<key>pop</key>
				<true/>
				<key>scope</key>
				<string>checkbox-onhold.characteristik.markdown-nice</string>
			</dict>
			<dict>
				<key>match</key>
				<string>\?</string>
				<key>pop</key>
				<true/>
				<key>scope</key>
				<string>checkbox-waiting.characteristik.markdown-nice</string>
			</dict>
		</array>
		<key>inside_string</key>
		<array>
			<dict>
				<key>meta_include_prototype</key>
				<false/>
			</dict>
			<dict>
				<key>meta_scope</key>
				<string>string.quoted.double.markdown-nice</string>
			</dict>
			<dict>
				<key>match</key>
				<string>\.</string>
				<key>scope</key>
				<string>constant.character.escape.markdown-nice</string>
			</dict>
			<dict>
				<key>match</key>
				<string>"</string>
				<key>pop</key>
				<true/>
				<key>scope</key>
				<string>punctuation.definition.string.end.markdown-nice</string>
			</dict>
		</array>
		<key>keywords</key>
		<array>
			<dict>
				<key>match</key>
				<string>\b(if|else|for|while)\b</string>
				<key>scope</key>
				<string>keyword.control.markdown-nice</string>
			</dict>
		</array>
		<key>lists</key>
		<array>
			<dict>
				<key>match</key>
				<string>^\s(\*|\+|\-)\s</string>
				<key>scope</key>
				<string>level1-ul.lists.markdown-nice</string>
			</dict>
			<dict>
				<key>match</key>
				<string>^\s\s\s(\*|\+|\-)\s</string>
				<key>scope</key>
				<string>level2-ul.lists.markdown-nice</string>
			</dict>
			<dict>
				<key>match</key>
				<string>^\s\s\s\s\s(\*|\+|\-)\s</string>
				<key>scope</key>
				<string>level3-ul.lists.markdown-nice</string>
			</dict>
			<dict>
				<key>match</key>
				<string>^\s\s\s\s\s\s\s(\*|\+|\-)\s</string>
				<key>scope</key>
				<string>level4-ul.lists.markdown-nice</string>
			</dict>
			<dict>
				<key>match</key>
				<string>^\s\s\s\s\s\s\s\s\s(\*|\+|\-)\s</string>
				<key>scope</key>
				<string>level5-ul.lists.markdown-nice</string>
			</dict>
			<dict>
				<key>match</key>
				<string>^\s([0-9]+)\.\s</string>
				<key>scope</key>
				<string>level1-ol.lists.markdown-nice</string>
			</dict>
			<dict>
				<key>match</key>
				<string>^\s+([0-9]+)\.([0-9]+)\.\s</string>
				<key>scope</key>
				<string>level2-ol.lists.markdown-nice</string>
			</dict>
			<dict>
				<key>match</key>
				<string>^\s+([0-9]+)\.([0-9]+)\.([0-9]+)\.\s</string>
				<key>scope</key>
				<string>level3-ol.lists.markdown-nice</string>
			</dict>
			<dict>
				<key>match</key>
				<string>^\s+([0-9]+)\.([0-9]+)\.([0-9]+)\.([0-9]+)\.\s</string>
				<key>scope</key>
				<string>level4-ol.lists.markdown-nice</string>
			</dict>
			<dict>
				<key>match</key>
				<string>^\s+([0-9]+)\.([0-9]+)\.([0-9]+)\.([0-9]+)\.([0-9]+)\.\s</string>
				<key>scope</key>
				<string>level5-ol.lists.markdown-nice</string>
			</dict>
		</array>
		<key>main</key>
		<array>
			<dict>
				<key>include</key>
				<string>keywords</string>
			</dict>
			<dict>
				<key>include</key>
				<string>strings</string>
			</dict>
			<dict>
				<key>include</key>
				<string>characteristiks</string>
			</dict>
			<dict>
				<key>include</key>
				<string>headlines</string>
			</dict>
			<dict>
				<key>include</key>
				<string>lists</string>
			</dict>
		</array>
		<key>strings</key>
		<array>
			<dict>
				<key>match</key>
				<string>"</string>
				<key>push</key>
				<string>inside_string</string>
				<key>scope</key>
				<string>punctuation.definition.string.begin.markdown-nice</string>
			</dict>
		</array>
	</dict>
	<key>file_extensions</key>
	<array>
		<string>nmd</string>
	</array>
	<key>name</key>
	<string>NiceMarkdown</string>
	<key>scope</key>
	<string>source.markdown-nice</string>
	<key>variables</key>
	<dict>
		<key>ident</key>
		<string>[A-Za-z_][A-Za-z_0-9]*</string>
	</dict>
</dict>
</plist>
